### ISSUE TITLE
Error attempt to insert nil object from objects

### ISSUE THREAD

**Issue by emirdeliz** [xfumihiro/react-native-image-to-base64#1]
I'm using iphone 4s with code:

```
RNImageToBase64.getBase64String('file:///var/mobile/Containers/Data/Application/CFC50BF5-19D0-4C40-B362-1CFC25888F86/Documents/5276B443-6112-4837-A053-67F020A0BD67.jpg', (err, base64) => {
     console.log(base64);
}); 
```

After running the error is displayed:

> 2016-09-26 19:18:25.857 AppBico[258:26030] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'
> **\* First throw call stack:
> (0x2464f91b 0x23deae17 0x24564871 0x2456ea21 0x2adf5b 0x2d2b90d5 0x6c2b7f 0x6ceecf 0x6ce7cf 0x24381b29 0x24381718)
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by emirdeliz** [comment]
I found the problem. The path was nothing of the library. After change this works fine for me! Thanks!

**Comment by swaroopa94** [comment]
Hi,
Can you tell me how did you solve this..

**Comment by emirdeliz** [comment]
@swaroopa94 look here https://github.com/emirdeliz/react-native-app-bico/blob/fab80a1d43a03627ce94f9448b348437d1d735d8/src/client/screens/account-edit/component/index.js

**Comment by swaroopa94** [comment]
Hi,
Thanks for the response ,
Her I am not uploading or capturing the image I am just getting an url from api, I have to convert that and and store that base64 image

**Comment by emirdeliz** [comment]
You can save and then pass the file as my example

**Comment by swaroopa94** [comment]
ya when I was saving the uri then its throwing an error
