### ISSUE TITLE
Callback function crashes

### ISSUE THREAD

**Issue by Psiiirus** [xfumihiro/react-native-image-to-base64#3]
Hi,
I tried to use this module but unfortunately I cant get it work.
Any clue whats wrong? :/

"react-native": "0.35.0"

```
console.log("do uploadPicture",this.state.capturedImage.path,RNImageToBase64 ); // works fine
RNImageToBase64.getBase64String(this.state.capturedImage.path, function(err, imageBase64) {
... 
});
```

Xcode error
<img width="916" alt="bildschirmfoto 2016-10-21 um 01 02 55" src="https://cloud.githubusercontent.com/assets/593363/19581038/a02d9688-972a-11e6-895c-d78b02ade989.png">

**Comment by Psiiirus** [comment]
Do i need to set special privacy settings?!

**Comment by Psiiirus** [comment]
I think i got it.

It seems that ALAssetsLibrary is deprecated and removed since SDK 10.0 like all other ALAsset related libs.

Unfortunately I don't really get how to change it because of not having any objective-c background

´´´
...
NS_CLASS_DEPRECATED_IOS(4_0, 9_0, "Use PHPhotoLibrary from the Photos framework instead")
@interface ALAssetsLibrary : NSObject {
...

// Returns an ALAssetRepresentation object for the default representation of the ALAsset
- (ALAssetRepresentation *)defaultRepresentation NS_DEPRECATED_IOS(4_0, 9_0, "Use PHImageRequestOptions with the PHImageManager from the Photos framework instead");
  ....

´´´

Would be awesome if you can have a look @xfumihiro .

**Comment by cherniv** [comment]
Right, it is not possible to use this library now :( ..

**Comment by joypatel04** [comment]
@MM-Psiiirus Is there any updates? you solved it or something else you are using?

**Comment by joypatel04** [comment]
@xfumihiro Can you please take a look at it and give an update? Is this issue still there or not?

**Comment by dyguests** [comment]
same issue.OTL.
is there anyway else?
:(

**Comment by Psiiirus** [comment]
in my case I needed a base64 captured camera image so i just chose another camera bundle which provided an asset-uri and a base64. :/

**Comment by Psiiirus** [comment]
@dyguests , @joypatel04 i just came along the ImageStore...maybe this can help you solve the problem without this npm-package

https://facebook.github.io/react-native/docs/imagestore.html#getbase64fortag

```
ImageStore.getBase64ForTag("file://" +imageURI.uri,(data) =>
      {
        console.log('getBase64ForTag',data);
        this.setState({
          ...this.state,
          capturedImage: {data,uri: imageURI.uri },
          isLoading: false
        });
      },(e) => {
          console.log('getBase64ForTag-error',e);
        this.setState({
          ...this.state,
          isLoading: false
        });
      });
```

**Comment by muszu** [comment]
For me (iOS 10) ImageStore don't work.
I created PR where I handle only local files, but I'm going to make it work with normal url and add handling errors.

**Comment by minhphung210** [comment]
you can use  https://github.com/itinance/react-native-fs

      RNFS.readFile(path, 'base64')
      .then((data) => console.log(data))
      .catch((err) => console.log(err)); 
    });
